### ISSUE TITLE
As Juliana, I would like to make sure that feedback is ROUTED to the correct stakeholder so that if an angry user writes pointed feedback, it does not get lost as process feedback

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#259]
- [x] We should add a question to the survey that says what division they were in (maybe?) #300
- [x] We should get a list of shareholders of what feedback should go to which particular section
- [ ] #298
- [x] We should verify that we mention in the survey that specific feedback will go to a particular shareholder #299
- [x] Add language that will users will be anonymized unless you provide identifying information #301
- [x] #252 
- [ ] If someone answers ‘yes’ to the ‘Do you want someone to follow up with you’ or types anything in the ‘any other question or comment’ comment box of either inspection or PIC surveys, that survey will be emailed immediately to the appropriate chief for follow up.
- [ ]   Dashboards with weekly info will be created
- [ ]   Standard monthly reports of survey breakdowns by question (with anecdotal info entered by respondent exposed in the report) will be generated for all PIC survey responses, all inspection survey responses, and responses by inspection type/PIC area type.
- [ ]   Access to full data responses will be available for further noodling/data reporting.

**Comment by ErnieAtLYD** [comment]
@mathias-gibson - can you handle this?

**Comment by mathias-gibson** [comment]
yeah, already have a list of departments and accompanying emails for routing. for the logic we should only route if they add content to the open text box questions

**Comment by mathias-gibson** [comment]
seems like this should be split out into issues for you and issues for me

**Comment by ErnieAtLYD** [comment]
@mathias-gibson: Yeah definitely. Can you link me the file where the list of routing is available?

Also assuming that doing the routing through typeform is okay, for now?

**Comment by mathias-gibson** [comment]
what does routing through typeform look like? what about text feedback? I
think we may just want to route role, dept and open text fields, and only
route if open text fields have text in them, (excluding fields that only
have "no"  or "na," which will be common in the text submission to move
along in the progression​)

i'll send the contacts in slack

**Comment by ErnieAtLYD** [comment]
Ooof.

So I just took a look at the typeform routing options. They're not as easy
on Typeform as I thought - you either have an option to e-mail a certain
set of employees once a user has sent a form, no matter what section
they've chosen. There may be some hacking we can do involving e-mails
inside hidden fields but that doesn't seem to be so scalable.

I think the best thing to do from a high level would be to do the routing
logic on the python side and feed it into the app after all. Not as cut and
dry as doing it as Typeform and we'll have to spin off a new issue talking
about how to build this out and stuff
